### PR TITLE
Add fixes and cleanup to integration tests

### LINKED ISSUE #23: Change integration tests to not depend on a certain count of tests
The integration tests should check for the existence of the tests rather than looking for a certain count.

### LINKED ISSUE #24: Fix typo in integration test npm command
One of the steps has an npm command that has a typo: `create-test-file-browserifed-tape`

### LINKED ISSUE #25: Make it easier to debug errors in integration tests
1. Add a bash script to build locally easily
2. Add documentation for how to open up the index.html for each bundler test.

### LINKED ISSUE #92: Make it easier to debug errors in integration tests
1. Add a bash script to build locally easily
2. Add documentation for how to open up the index.html for each bundler test.

### LINKED ISSUE #93: Change integration tests to not depend on a certain count of tests
The integration tests should check for the existence of the tests rather than looking for a certain count.

### LINKED ISSUE #94: Fix typo in integration test npm command
One of the steps has an npm command that has a typo: `create-test-file-browserifed-tape`

### PR DESCRIPTION
**Pull request by katelynsills**
## Description
This PR adds a number of small fixes to the integration tests. It:

1. Moves the build/bundle process for the integration tests to bash scripts that can be run locally as well as as a step in CircleCI.
2. Simplifies CircleCI by adding aliases for the reused steps. (Unfortunately, YAML has no mechanism for this sort of thing for sequences, only maps and scalars, so we have to save the steps individually.)
3. Fixes typos and removes hardcoded test number
4. Adds more documentation for debugging the integration test results and testing locally.
5. Grabs the page error from the browser tests (if any) and console.logs it to be visible in CircleCI logs. 

Closes #23, closes #24, closes #25

## Test
You can use the CircleCI command line tool to test locally:
`circleci local execute --job test_integration`
`circleci local execute --job post_release_test_integration`

### CODE REVIEW

File: integration-test/scripts/build-pre-release-test.sh [hunk 1]
```diff
@@ -0,0 +1,11 @@
+npm run-script build
```
Comment (warner) [inline integration-test/scripts/build-pre-release-test.sh:2]: let's add a check that these are run from the top-level directory.. I happened to switch into `integration-test/` and then ran `./scripts/build-pre-release-test.sh` and it failed confusingly.

Maybe put a `#! /bin/sh -e` on the first line, then on the second line do a `cd integration-test ; cd ..`. That will fail if there's no `integration-test` directory to switch into (which will be the case from anywhere but the top directory), and then the `-e` means that error will halt the rest of the script. If it succeeds, we'll be back at the top directory, so the rest of the script won't need to be changed.

**Review by warner — APPROVED** [review]
Maybe also move scaffolding/ to something like `browser-tests` and `post-release-browser-tests`, with a `browser-tests/README` that says "load each of these directories in a web browser and look at the console for `Tests: passed`" or something.
